Path: "D:\\Documents\\Work\\HZB\\Scripts\\Python\\refractive_index_database\\data"
File: "database123.csv"
Interactive: true     #for jupyter interfactive editing
Modules:     # which databases to include
  UserData: true
  RefractiveIndexInfo: true
  Filmetrics: true
ReferenceSpectrum:     # evaluate n and k at given spectral value
  Value: 632.8
  SpectrumType: wavelength
  Unit: nanometer
